### ISSUE TITLE
Backdoor in upstream xz/lzma

### ISSUE THREAD

**Issue by amousset** [Portable-Network-Archive/liblzma-rs#95]
See https://www.openwall.com/lists/oss-security/2024/03/29/4

This library is very likely not impacted as it does not use the tarball which contains the backdoor activation but directly the git repository as a submodule, but it might be worth considering a downgrade to 5.4.6 as a safety measure.

**Comment by ChanTsune** [comment]
@amousset 
Thank you for letting us know! We'll be keeping an eye on this matter!
